# Generated by Django 4.1.7 on 2023-03-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitkaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkExpanseGroupUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LinkExpanseGroupUser_created_at', models.DateTimeField(auto_now_add=True)),
                ('LinkExpanseGroupUser_updated_at', models.DateTimeField(auto_now=True)),
                ('LinkExpanseGroupUser_is_active', models.BooleanField(default=True)),
                ('LinkExpanseGroupUser_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinkExpanseGroupUser_group_id', to='splitkaro.expansegroup')),
                ('LinkExpanseGroupUser_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LinkExpanseGroupUser_user_id', to='splitkaro.user')),
            ],
        ),
    ]
