# Generated by Django 4.1.7 on 2023-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitkaro', '0002_linkexpansegroupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansegroupuser',
            name='ExpanseGroupUser_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expansegroupuser',
            name='ExpanseGroupUser_Note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expansegroupuser',
            name='ExpanseGroupUser_amount',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='expansegroupuser',
            name='ExpanseGroupUser_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
